import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";


import "./globals.css";
import Providers from "@/components/Providers";
const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSlab.className}`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
